name: Deploy Microservices to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 619071337012.dkr.ecr.ap-south-1.amazonaws.com
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push user-service image
        run: |
          docker build -t $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-user/user-service:latest ./user
          docker tag $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-user/user-service:latest $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-user/user-service:${{ github.sha }}
          docker push $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-user/user-service:${{ github.sha }}

      - name: Build, tag, and push workout-service image
        run: |
          docker build -t $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-workout/workout-service:latest ./workout
          docker tag $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-workout/workout-service:latest $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-workout/workout-service:${{ github.sha }}
          docker push $619071337012.dkr.ecr.ap-south-1.amazonaws.com/sample-microservice-workout/workout-service:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $ap-south-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name sample-cluster --region $ap-south-1

      - name: Deploy user-service to EKS
        run: |
          kubectl apply -f k8s/user-deployment.yaml
          kubectl apply -f k8s/user-service.yaml

      - name: Deploy workout-service to EKS
        run: |
          kubectl apply -f k8s/workout-deployment.yaml
          kubectl apply -f k8s/workout-service.yaml
